server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:D:\workspace\democode\sqlite3\demo.db
mybatis:
  mapper-locations: Mapper/*Mapper.xml
  type-aliases-package: com.example.entity